export const NAMEN = 250;
export const MaxName = NAMEN; // 128

export const MaxOutPut = NAMEN; // 128
export const MaxCode = NAMEN; // 128
export const MaxTimeCycle = 18;
export const MaxMasterCode = 1;
export const MaxTecUserCode = 1;
export const MaxExtKeys = 1;
export const MaxProxyLrn = NAMEN; // 205
export const MaxProxyLrn2 = NAMEN; // 205
export const MaxFloorValue = 60;
export const MaxMasageOn = 8;
export const MaxAnswerY_N = 16; // MUST ADJUST UP/DOWN
export const MaxRelayControl = 2;
export const MaxEraseAll = 4; // FIX7  MUST ADJUST UP/DOWN
export const MaxFASTstep = 1;
export const MaxSpeechLevel = 1;
export const MaxService = 12;
export const MaxType = 1;
export const MaxOfset = 1;
export const MaxNewNo = NAMEN;
export const MaxCommSpd = 1;
export const MaxTel1Num = NAMEN;
export const MaxTel2Num = NAMEN;
export const MaxTel3Num = NAMEN;
export const MaxTel4Num = NAMEN;
export const MaxTel5Num = NAMEN;
export const MaxTel6Num = NAMEN;
export const MaxRingingNum = 1;
export const MaxBusySogTone = 9;
export const MaxToneCodes = 1;
export const MaxConfirmTone = 1;
export const MaxSetReadTime = 1;
export const MaxSetReadTimer = 12;
export const MaxSaveTimerSta = 1;
export const MaxFamilyNo = 1;
export const MaxMDMCode = 1;
export const MaxRmtMasterCode = 1;
export const MaxKeepName = 1; // FIX7
export const MaxPrxyDirRly1 = 6; // PrxyFast
export const MaxPrxyDirRly2 = 6; // PrxyFast
export const MaxPrxyQtytRly1 = 6; // PrxyFast
export const MaxPrxyQtytRly2 = 6; // PrxyFast
export const MaxPRG_Was_Done = 1; // PRG SHOW
export const MaxORG_Was_Start = 1; // ORG start
export const MaxRelay1MeM = 1; // relay 1 status
export const MaxRelay2MeM = 1; // relay 2 status

export const CMaxName = 16;
export const CMaxOutPut = 3;
export const CMaxOrderNames = 1;
export const CMaxCode = 10;
export const CMaxTimeCycle = 2;
export const CMaxMasterCode = 10;
export const CMaxTecUserCode = 10;
export const CMaxExtKeys = 2;
export const CMaxProxyLrn = 8;
export const CMaxProxyLrn2 = 8;
export const CMaxFloorValue = 3;
export const CMaxMasageOn = 1;
export const CMaxAnswerY_N = 1;
export const CMaxRelayControl = 3;
export const CMaxEraseAll = 1;
export const CMaxFASTstep = 1;
export const CMaxSpeechLevel = 1;
export const CMaxService = 6;
export const CMaxType = 3;
export const CMaxOfset = 4;
export const CMaxNewNo = 3;
export const CMaxCommSpd = 1;
export const CMaxTel1Num = 15;
export const CMaxTel2Num = 15;
export const CMaxTel3Num = 15;
export const CMaxTel4Num = 15;
export const CMaxTel5Num = 15;
export const CMaxTel6Num = 15;
export const CMaxRingingNum = 2;
export const CMaxBusySogTone = 2;
export const CMaxToneCodes = 2;
export const CMaxConfirmTone = 1;
export const CMaxSetReadTime = 5;
export const CMaxSetReadTimer = 7;
export const CMaxSaveTimerSta = 1;
export const CMaxFamilyNo = 1;
export const CMaxMDMCode = 10;
export const CMaxRmtMasterCode = 10;
export const CMaxKeepName = 1; // FIX7
export const CMaxPrxyDirRly1 = NAMEN; // PrxyFast
export const CMaxPrxyDirRly2 = NAMEN; // PrxyFast
export const CMaxPrxyQtytRly1 = 16; // PrxyFast
export const CMaxPrxyQtytRly2 = 16; // PrxyFast
export const CMaxPRG_Was_Done = 1; // PRG SHOW
export const CMaxORG_Was_Start = 1; // ORG Start
export const CMaxRelay1MeM = 1; // relay 1 status
export const CMaxRelay2MeM = 1; // relay 2 status

// *********** System EEprom *****************
export const Status_SAC = 1;
export const Type = Status_SAC + 4;
export const MDMCode = Type + 16;
export const MasterCode = MDMCode + MaxMDMCode * CMaxMDMCode; // real code out of modem mape scope
export const TecUserCode = MasterCode + MaxMasterCode * CMaxMasterCode;
export const Code = TecUserCode + MaxTecUserCode * CMaxTecUserCode;
export const Name = Code + MaxCode * CMaxCode; // 1
export const OutPut = Name + MaxName * CMaxName * 2; // 7 /IMP
export const TimeCycle = OutPut + MaxOutPut * CMaxOutPut; // 7
export const ExtKeys = TimeCycle + MaxTimeCycle * CMaxTimeCycle; // 7
export const ProxyLrn = ExtKeys + MaxExtKeys * CMaxExtKeys; // 7
export const ProxyLrn2 = ProxyLrn + MaxProxyLrn * CMaxProxyLrn * 6; // 7   //IMP
export const MasageOn = ProxyLrn2 + MaxProxyLrn2 * CMaxProxyLrn2 * 6; // 7 //IMP
export const AnswerY_N = MasageOn + MaxMasageOn * CMaxMasageOn; // 7
export const FloorValue = AnswerY_N + MaxAnswerY_N * CMaxAnswerY_N;
export const RelayControl = FloorValue + MaxFloorValue * CMaxFloorValue;
export const EraseAll = RelayControl + MaxRelayControl * CMaxRelayControl;
export const FASTstep = EraseAll + MaxEraseAll * CMaxEraseAll;
export const SpeechLevel = FASTstep + MaxFASTstep * CMaxFASTstep;
export const Service = SpeechLevel + MaxSpeechLevel * CMaxSpeechLevel;
export const Ofset = Service + MaxService * CMaxService;
export const NewNo = Ofset + MaxOfset * CMaxOfset;
export const CommSpd = NewNo + MaxNewNo * CMaxNewNo;
export const Tel1Num = CommSpd + MaxCommSpd * CMaxCommSpd;
export const Tel2Num = Tel1Num + MaxTel1Num * CMaxTel1Num;
export const Tel3Num = Tel2Num + MaxTel2Num * CMaxTel2Num;
export const Tel4Num = Tel3Num + MaxTel3Num * CMaxTel3Num;
export const Tel5Num = Tel4Num + MaxTel4Num * CMaxTel4Num;
export const Tel6Num = Tel5Num + MaxTel5Num * CMaxTel5Num;
export const RingingNum = Tel6Num + MaxTel6Num * CMaxTel6Num;
export const BusySogTone = RingingNum + MaxRingingNum * CMaxRingingNum;
export const ToneCodes = BusySogTone + MaxBusySogTone * CMaxBusySogTone;
export const ConfirmTone = ToneCodes + MaxToneCodes * CMaxToneCodes;
export const SetReadTime = ConfirmTone + MaxConfirmTone * CMaxConfirmTone;
export const SetReadTimer = SetReadTime + MaxSetReadTime * CMaxSetReadTime;
export const SaveTimerSta = SetReadTimer + MaxSetReadTimer * CMaxSetReadTimer;
export const FamilyNo = SaveTimerSta + MaxSaveTimerSta * CMaxSaveTimerSta;
export const RmtMasterCode = FamilyNo + MaxFamilyNo * CMaxFamilyNo;
export const KeepName = RmtMasterCode + MaxRmtMasterCode * CMaxRmtMasterCode; // FIX7
export const PrxyDirRly1 = KeepName + MaxKeepName * CMaxKeepName;
export const PrxyDirRly2 = PrxyDirRly1 + MaxPrxyDirRly1 * CMaxPrxyDirRly1;
export const PrxyQtytRly1 = PrxyDirRly2 + MaxPrxyDirRly2 * CMaxPrxyDirRly2;
export const PrxyQtytRly2 = PrxyQtytRly1 + MaxPrxyQtytRly1 * CMaxPrxyQtytRly1;
export const PRG_Was_Done = PrxyQtytRly2 + MaxPrxyQtytRly2 * CMaxPrxyQtytRly2;
export const ORG_Was_Start = PRG_Was_Done + MaxPRG_Was_Done * CMaxPRG_Was_Done;
export const Relay1MeM = ORG_Was_Start + MaxORG_Was_Start * CMaxORG_Was_Start;
export const Relay2MeM = Relay1MeM + MaxRelay1MeM * CMaxRelay1MeM;
export const MaxEEprom = Relay2MeM + MaxRelay2MeM * CMaxRelay2MeM;
